(function(){
var SESSION_MS=20*60*1000,code=sessionStorage.getItem('visitorCode'),lastActivity=parseInt(sessionStorage.getItem('visitorLastActivity')||'0',10);if(code&&(!lastActivity||Date.now()-lastActivity>SESSION_MS)){sessionStorage.removeItem('visitorCode');sessionStorage.removeItem('visitorLastActivity');localStorage.removeItem('promotionCalculatorData');code=null}
function api(body){return fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(function(r){return r.text().then(function(t){try{return JSON.parse(t)}catch(e){throw new Error('تعذر الاتصال بقاعدة البيانات. أكمل إعداد الموقع من setup.php.')}})})}
function overlay(){var d=document.createElement('div');d.id='guestGate';d.style='position:fixed;inset:0;z-index:9999;background:#071f24dd;display:grid;place-items:center;padding:18px;direction:rtl';d.innerHTML='<div style="width:min(420px,100%);background:#fff;border-radius:24px;padding:22px;text-align:center"><h2>الدخول إلى الحاسبة</h2><button id="newGuest" class="ok">زائر جديد</button><div style="margin:12px">أو</div><input id="oldCode" class="control" inputmode="numeric" maxlength="4" placeholder="رقم زائر سابق"><button id="oldGuest" class="ok" style="margin-top:8px">استرجاع البيانات</button><p id="gateMsg" style="color:#b42318"></p></div>';document.body.appendChild(d);
document.getElementById('newGuest').onclick=function(){api({action:'new'}).then(function(x){if(!x.ok)throw Error(x.message);localStorage.removeItem('promotionCalculatorData');sessionStorage.setItem('visitorCode',x.code);sessionStorage.setItem('visitorLastActivity',String(Date.now()));code=x.code;d.querySelector('div').innerHTML='<h2>أنت الزائر رقم</h2><div style="font-size:50px;font-weight:bold;color:#0b6b62">'+x.code+'</div><button id="copyCode" class="ok">نسخ الرقم</button><p>للرجوع إلى البيانات المسجلة في هذه الجلسة يمكن استخدام رقم الزائر.</p><button id="continueGuest" class="ok">متابعة</button>';document.getElementById('copyCode').onclick=function(){navigator.clipboard&&navigator.clipboard.writeText(x.code)};document.getElementById('continueGuest').onclick=function(){d.remove();addGuestBar();startOnboarding()}}).catch(show)};
document.getElementById('oldGuest').onclick=function(){api({action:'restore',code:document.getElementById('oldCode').value}).then(function(x){if(!x.ok)throw Error(x.message);sessionStorage.setItem('visitorCode',x.code);sessionStorage.setItem('visitorLastActivity',String(Date.now()));code=x.code;if(x.data)localStorage.setItem('promotionCalculatorData',JSON.stringify(x.data));location.reload()}).catch(show)};function show(e){document.getElementById('gateMsg').textContent=e.message}}
if(!code)overlay();
function touchActivity(){if(code)sessionStorage.setItem('visitorLastActivity',String(Date.now()))}['click','input','change','keydown','touchstart','scroll'].forEach(function(n){document.addEventListener(n,touchActivity,{passive:true})});
var endingSession=false;function endGuestSession(reason){if(endingSession)return;endingSession=true;var raw=localStorage.getItem('promotionCalculatorData'),done=Promise.resolve();if(code&&raw){try{done=api({action:'save',code:code,data:JSON.parse(raw)})}catch(e){}}var oldCode=code,finish=function(){if(oldCode)api({action:'logout',code:oldCode});sessionStorage.removeItem('visitorCode');sessionStorage.removeItem('visitorLastActivity');localStorage.removeItem('promotionCalculatorData');location.reload()};done.then(finish,finish)}
function addGuestBar(){if(!code||document.getElementById('guestLogout'))return;var b=document.createElement('button');b.type='button';b.id='guestLogout';b.textContent='الخروج من وضع الزائر';b.style='display:block;margin:10px auto 0;padding:8px 14px;border:1px solid #0b6b62;border-radius:10px;background:#fff;color:#0b6b62;font-family:Tahoma;cursor:pointer';b.onclick=function(){endGuestSession('manual')};var shell=document.querySelector('.shell');if(shell)shell.appendChild(b)}if(code)addGuestBar();
setInterval(function(){var t=parseInt(sessionStorage.getItem('visitorLastActivity')||'0',10);if(code&&t&&Date.now()-t>=SESSION_MS)endGuestSession('inactive')},30000);
var onboardingStage=0;function startOnboarding(){onboardingStage=1;var b=document.querySelector('[data-date="rankDate"]');if(b)b.click()}
var dateOk=document.getElementById('dateOk');if(dateOk)dateOk.addEventListener('click',function(){if(onboardingStage===1){onboardingStage=2;setTimeout(function(){var b=document.querySelector('[data-date="closeDate"]');if(b)b.click();setTimeout(function(){var d=document.getElementById('dateDay'),m=document.getElementById('dateMonth'),y=document.getElementById('dateYear');if(d&&m&&y){d.value='29';m.value='12';y.value='1447';d.dispatchEvent(new Event('change',{bubbles:true}))}},30)},30)}else if(onboardingStage===2){onboardingStage=3;setTimeout(function(){var b=document.getElementById('performanceBtn');if(b)b.click()},30)}});
var perfOk=document.getElementById('perfOk');if(perfOk)perfOk.addEventListener('click',function(){if(onboardingStage===3)onboardingStage=0});
var lastSaved='';function sync(){if(!code)return;var raw=localStorage.getItem('promotionCalculatorData')||'';if(raw&&raw!==lastSaved){lastSaved=raw;try{api({action:'save',code:code,data:JSON.parse(raw)})}catch(e){}}}setInterval(sync,2000);window.addEventListener('pagehide',sync);var calc=document.getElementById('calculateBtn');if(calc)calc.addEventListener('click',function(){setTimeout(sync,300)});
})();
