(function(){
var SESSION_MS=20*60*1000,code=sessionStorage.getItem('visitorCode'),lastActivity=parseInt(sessionStorage.getItem('visitorLastActivity')||'0',10);if(code&&(!lastActivity||Date.now()-lastActivity>SESSION_MS)){sessionStorage.removeItem('visitorCode');sessionStorage.removeItem('visitorLastActivity');sessionStorage.removeItem('visitorOnboardingVersion');localStorage.removeItem('promotionCalculatorData');code=null}
function api(body){return fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(function(r){return r.text().then(function(t){try{return JSON.parse(t)}catch(e){throw new Error('تعذر الاتصال بقاعدة البيانات. أكمل إعداد الموقع من setup.php.')}})})}
function overlay(){var d=document.createElement('div');d.id='guestGate';d.style='position:fixed;inset:0;z-index:9999;background:#071f24dd;display:grid;place-items:center;padding:18px;direction:rtl';d.innerHTML='<div style="width:min(420px,100%);background:#fff;border-radius:24px;padding:22px;text-align:center"><h2>الدخول إلى الحاسبة</h2><button id="newGuest" class="ok">زائر جديد</button><div style="margin:12px">أو</div><input id="oldCode" class="control" inputmode="numeric" maxlength="4" placeholder="رقم زائر سابق"><button id="oldGuest" class="ok" style="margin-top:8px">استرجاع البيانات</button><p id="gateMsg" style="color:#b42318"></p></div>';document.body.appendChild(d);
document.getElementById('newGuest').onclick=function(){api({action:'new'}).then(function(x){if(!x.ok)throw Error(x.message);localStorage.removeItem('promotionCalculatorData');sessionStorage.removeItem('visitorOnboardingVersion');sessionStorage.setItem('visitorCode',x.code);sessionStorage.setItem('visitorLastActivity',String(Date.now()));code=x.code;d.querySelector('div').innerHTML='<h2>أنت الزائر رقم</h2><div style="font-size:50px;font-weight:bold;color:#0b6b62">'+x.code+'</div><p>للرجوع إلى البيانات المسجلة في هذه الجلسة يمكن استخدام رقم الزائر.</p><button id="continueGuest" class="ok">نسخ الرقم والمتابعة</button>';document.getElementById('continueGuest').onclick=function(){if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(x.code).catch(function(){});d.remove();addGuestBar();showRankStep()}}).catch(show)};
document.getElementById('oldGuest').onclick=function(){api({action:'restore',code:document.getElementById('oldCode').value}).then(function(x){if(!x.ok)throw Error(x.message);sessionStorage.setItem('visitorCode',x.code);sessionStorage.setItem('visitorLastActivity',String(Date.now()));sessionStorage.setItem('visitorOnboardingVersion','2');code=x.code;if(x.data)localStorage.setItem('promotionCalculatorData',JSON.stringify(x.data));location.reload()}).catch(show)};function show(e){document.getElementById('gateMsg').textContent=e.message}}
if(!code)overlay();
function touchActivity(){if(code)sessionStorage.setItem('visitorLastActivity',String(Date.now()))}['click','input','change','keydown','touchstart','scroll'].forEach(function(n){document.addEventListener(n,touchActivity,{passive:true})});
var endingSession=false;function endGuestSession(reason){if(endingSession)return;endingSession=true;var raw=localStorage.getItem('promotionCalculatorData'),done=Promise.resolve();if(code&&raw){try{done=api({action:'save',code:code,data:JSON.parse(raw)})}catch(e){}}var oldCode=code,finish=function(){if(oldCode)api({action:'logout',code:oldCode});sessionStorage.removeItem('visitorCode');sessionStorage.removeItem('visitorLastActivity');sessionStorage.removeItem('visitorOnboardingVersion');localStorage.removeItem('promotionCalculatorData');location.reload()};done.then(finish,finish)}
function addGuestBar(){if(!code||document.getElementById('guestLogout'))return;var b=document.createElement('button');b.type='button';b.id='guestLogout';b.textContent='الخروج من وضع الزائر';b.style='display:block;margin:10px auto 0;padding:8px 14px;border:1px solid #0b6b62;border-radius:10px;background:#fff;color:#0b6b62;font-family:Tahoma;cursor:pointer';b.onclick=function(){endGuestSession('manual')};var shell=document.querySelector('.shell');if(shell)shell.appendChild(b)}if(code)addGuestBar();
setInterval(function(){var t=parseInt(sessionStorage.getItem('visitorLastActivity')||'0',10);if(code&&t&&Date.now()-t>=SESSION_MS)endGuestSession('inactive')},30000);
var onboardingStage=0;function showRankStep(){var old=document.getElementById('rankGate');if(old)old.remove();var d=document.createElement('div');d.id='rankGate';d.style='position:fixed;inset:0;z-index:10000;background:#071f24dd;display:grid;place-items:center;padding:18px;direction:rtl';d.innerHTML='<div style="width:min(440px,100%);background:#fff;border-radius:24px;padding:22px"><h2 style="text-align:center;margin-top:0">اختر نوع الترشيح</h2><label class="radio-card"><input type="radio" name="guestRank" value="low"><span>المرتبة العاشرة فما دون</span></label><label class="radio-card" style="margin-top:10px"><input type="radio" name="guestRank" value="high"><span>المرتبة الحادية عشرة وأعلى</span></label><p id="rankGateMsg" style="color:#b42318;text-align:center;min-height:24px"></p><button id="saveGuestRank" class="ok">حفظ ومتابعة</button></div>';document.body.appendChild(d);document.getElementById('saveGuestRank').onclick=function(){var selected=document.querySelector('input[name="guestRank"]:checked');if(!selected){document.getElementById('rankGateMsg').textContent='يجب اختيار نوع الترشيح أولًا.';return}var target=document.querySelector('input[name="rank"][value="'+selected.value+'"]');if(target){target.checked=true;target.dispatchEvent(new Event('change',{bubbles:true}))}sessionStorage.setItem('visitorOnboardingVersion','2');d.remove();startOnboarding()}}
function startOnboarding(){onboardingStage=1;document.body.classList.add('guest-onboarding');var b=document.querySelector('[data-date="rankDate"]');if(b)b.click()}
var dateOk=document.getElementById('dateOk');if(dateOk)dateOk.addEventListener('click',function(){if(onboardingStage===1){onboardingStage=2;setTimeout(function(){var b=document.querySelector('[data-date="closeDate"]');if(b)b.click();setTimeout(function(){var d=document.getElementById('dateDay'),m=document.getElementById('dateMonth'),y=document.getElementById('dateYear');if(d&&m&&y){d.value='29';m.value='12';y.value='1447';d.dispatchEvent(new Event('change',{bubbles:true}))}},30)},30)}else if(onboardingStage===2){onboardingStage=3;setTimeout(function(){var b=document.getElementById('performanceBtn');if(b)b.click()},30)}});
var perfOk=document.getElementById('perfOk');if(perfOk)perfOk.addEventListener('click',function(){if(onboardingStage===3){onboardingStage=0;document.body.classList.remove('guest-onboarding')}});
document.addEventListener('click',function(e){if(onboardingStage>0&&e.target&&e.target.classList&&(e.target.classList.contains('close')||e.target.classList.contains('modal-bg'))){e.preventDefault();e.stopImmediatePropagation()}},true);
var onboardingStyle=document.createElement('style');onboardingStyle.textContent='.guest-onboarding #dateModal .close,.guest-onboarding #perfModal .close{display:none!important}';document.head.appendChild(onboardingStyle);
if(code&&!document.getElementById('guestGate')&&sessionStorage.getItem('visitorOnboardingVersion')!=='2')setTimeout(showRankStep,0);
var lastSaved='';function sync(){if(!code)return;var raw=localStorage.getItem('promotionCalculatorData')||'';if(raw&&raw!==lastSaved){lastSaved=raw;try{api({action:'save',code:code,data:JSON.parse(raw)})}catch(e){}}}setInterval(sync,2000);window.addEventListener('pagehide',sync);var calc=document.getElementById('calculateBtn');if(calc)calc.addEventListener('click',function(){setTimeout(sync,300)});
})();
